#	 World life expectancy project Exploratory Data Analysis (EDA) 

SELECT COUNTRY, MAX(`Life expectancy`), MIN(`Life expectancy`),
ROUND(MAX(`Life expectancy`)-MIN(`Life expectancy`), 1) AS Life_Increase_15_Years
FROM world_life_expectancy
GROUP BY Country
HAVING MIN(`Life expectancy`) <> 0
AND MAX(`Life expectancy`) <> 0
ORDER BY Life_Increase_15_Years DESC;


-- AVERAGE LIFE EXPECTANCY 

SELECT YEAR, ROUND(AVG(`Life expectancy`),2)
FROM world_life_expectancy
# WHERE `Life expectancy` <> 0
GROUP BY YEAR
ORDER BY YEAR;


-- LET'S CHK COORELATION BETWEEN GDP AND LIFE EXPECTANCY
-- LIKE IF A COUNTRY MAKING LOT OF MONEY, IF THEIR GDP IS HIGH WHAT'S IT'S RELATION WITH LIFE EXPECATANXCY OF THAT COUNTRY

SELECT COUNTRY, `Life expectancy`, GDP
FROM world_life_expectancy;

-- LETS CHK AVG OF BOTH

SELECT COUNTRY, ROUND(AVG(`Life expectancy`),1) AS Life_Exp, ROUND(AVG(GDP), 1) AS GDP
FROM world_life_expectancy
GROUP BY COUNTRY
HAVING Life_Exp > 0
AND GDP > 0
ORDER BY GDP desc;


-- CORRELATION FROM HIGH GDP TO HIGH LIFE EXPECTANCY AND VICE VERSA 

SELECT
SUM(CASE WHEN GDP >= 1500 THEN 1 ELSE 0 END) High_Gdp_Count,
AVG(CASE WHEN GDP >= 1500 THEN `Life expectancy` ELSE NULL END) High_Gdp_Life_Expectancy,
SUM(CASE WHEN GDP >= 1500 THEN 1 ELSE 0 END) Low_Gdp_Count,
AVG(CASE WHEN GDP >= 1500 THEN 1 ELSE `Life expectancy` END) Low_Gdp_Life_Expectancy
FROM world_life_expectancy;


SELECT *
FROM world_life_expectancy;


-- CHECK AVG LIFE EXPECTANCY BETWEEN STATUS

SELECT STATUS, ROUND(AVG(`Life expectancy`), 2)
FROM world_life_expectancy
GROUP BY STATUS; 

-- REASON BY DEVELOPED NATIONS HAVE HIGH AVG BECZ OF LESS IN NUMBER CHK BELOW, SO THIS CORREELATION DOSNT FILL THE PURPOSE FOR SOME PEOPLE I GUESS

SELECT STATUS, COUNT(DISTINCT COUNTRY), ROUND(AVG(`Life expectancy`), 2)
FROM world_life_expectancy
GROUP BY STATUS; 


-- BMI


SELECT COUNTRY, ROUND(AVG(`Life expectancy`),1) AS Life_Exp, ROUND(AVG(BMI), 1) AS BMI
FROM world_life_expectancy
GROUP BY COUNTRY
HAVING Life_Exp > 0
AND BMI > 0
ORDER BY BMI ASC;


-- LETS CHECK ADULTY MORTALITY
-- COORETALTION => HOW MANY PEOPLE DYING EACH YEAR IN A COUNTRY AND IS THAT A LOT COMPARE TO THEIR LIFE EXPECTANCY


SELECT COUNTRY,
YEAR,
`Life expectancy`,
`Adult Mortality`,
SUM(`Adult Mortality`) OVER(PARTITION BY COUNTRY ORDER BY YEAR) AS Rolling_Total
FROM world_life_expectancy
WHERE COUNTRY LIKE '%UNITED%';


-- WE CAN ADD TOTAL POPULATION BY JOINING TOTAL POPULATION DATA TABLE BECZ WE DONT HAVE TOTAL POP DATA IN CURRENT DATASET AND COMPARE IT WITH ADULT MORTALITY



